DROP TABLE XXQGEN.XXQGEN_APPL_INTF CASCADE CONSTRAINTS;

CREATE TABLE XXQGEN.XXQGEN_APPL_INTF
(
  LINE_ID            NUMBER,
  HEADER_ID          NUMBER,
  RECORD_TYPE        VARCHAR2(240 BYTE),
  PROCESS_FLAG       VARCHAR2(5 BYTE)           DEFAULT 'N',
  IDENTIFIER1        VARCHAR2(240 BYTE),
  IDENTIFIER2        VARCHAR2(240 BYTE),
  IDENTIFIER3        VARCHAR2(240 BYTE),
  IDENTIFIER4        VARCHAR2(240 BYTE),
  IDENTIFIER5        VARCHAR2(240 BYTE),
  SEGMENT1           VARCHAR2(240 BYTE),
  SEGMENT2           VARCHAR2(240 BYTE),
  SEGMENT3           VARCHAR2(240 BYTE),
  SEGMENT4           VARCHAR2(240 BYTE),
  SEGMENT5           VARCHAR2(240 BYTE),
  SEGMENT6           VARCHAR2(240 BYTE),
  SEGMENT7           VARCHAR2(240 BYTE),
  SEGMENT8           VARCHAR2(240 BYTE),
  SEGMENT9           VARCHAR2(240 BYTE),
  SEGMENT10          VARCHAR2(240 BYTE),
  ATTRIBUTE1         VARCHAR2(240 BYTE),
  ATTRIBUTE2         VARCHAR2(240 BYTE),
  ATTRIBUTE3         VARCHAR2(240 BYTE),
  ATTRIBUTE4         VARCHAR2(240 BYTE),
  ATTRIBUTE5         VARCHAR2(240 BYTE),
  ATTRIBUTE6         VARCHAR2(240 BYTE),
  ATTRIBUTE7         VARCHAR2(240 BYTE),
  ATTRIBUTE8         VARCHAR2(240 BYTE),
  ATTRIBUTE9         VARCHAR2(240 BYTE),
  ATTRIBUTE10        VARCHAR2(240 BYTE),
  ATTRIBUTE11        VARCHAR2(240 BYTE),
  ATTRIBUTE12        VARCHAR2(240 BYTE),
  ATTRIBUTE13        VARCHAR2(240 BYTE),
  ATTRIBUTE14        VARCHAR2(240 BYTE),
  ATTRIBUTE15        VARCHAR2(240 BYTE),
  ATTRIBUTE16        VARCHAR2(240 BYTE),
  ATTRIBUTE17        VARCHAR2(240 BYTE),
  ATTRIBUTE18        VARCHAR2(240 BYTE),
  ATTRIBUTE19        VARCHAR2(240 BYTE),
  ATTRIBUTE20        VARCHAR2(240 BYTE),
  ATTRIBUTE21        VARCHAR2(240 BYTE),
  ATTRIBUTE22        VARCHAR2(240 BYTE),
  ATTRIBUTE23        VARCHAR2(240 BYTE),
  ATTRIBUTE24        VARCHAR2(240 BYTE),
  ATTRIBUTE25        VARCHAR2(240 BYTE),
  ATTRIBUTE26        VARCHAR2(240 BYTE),
  ATTRIBUTE27        VARCHAR2(240 BYTE),
  ATTRIBUTE28        VARCHAR2(240 BYTE),
  ATTRIBUTE29        VARCHAR2(240 BYTE),
  ATTRIBUTE30        VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE1   VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE2   VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE3   VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE4   VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE5   VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE6   VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE7   VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE8   VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE9   VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE10  VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE11  VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE12  VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE13  VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE14  VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE15  VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE16  VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE17  VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE18  VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE19  VARCHAR2(240 BYTE),
  EXTRA_ATTRIBUTE20  VARCHAR2(240 BYTE),
  ENABLED_FLAG       VARCHAR2(1 BYTE),
  START_DATE         DATE,
  END_DATE           DATE,
  ERROR_MESSAGE      VARCHAR2(4000 BYTE),
  REQUEST_ID         NUMBER,
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_LOGIN  NUMBER,
  ATTRIBUTE130       VARCHAR2(240 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE INDEX XXQGEN.XXQGEN_APPL_INTF_N1 ON XXQGEN.XXQGEN_APPL_INTF
(REQUEST_ID, RECORD_TYPE)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX XXQGEN.XXQGEN_APPL_INTF_N2 ON XXQGEN.XXQGEN_APPL_INTF
(REQUEST_ID, PROCESS_FLAG)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
