DROP TABLE XXQGEN.XXQGEN_CASH_RECEIPT_STG CASCADE CONSTRAINTS;

CREATE TABLE XXQGEN.XXQGEN_CASH_RECEIPT_STG
(
  STG_REC_ID         NUMBER,
  SERVICE_LINE       VARCHAR2(100 BYTE),
  INVOICE_NUMBER     VARCHAR2(100 BYTE),
  REFERENCE_NUMBER   VARCHAR2(100 BYTE),
  PAYMENT_DATE       DATE,
  REMITTANCE_NUMBER  NUMBER,
  PO_NUMBER          VARCHAR2(100 BYTE),
  PAYMENT_AMOUNT     NUMBER,
  CUSTOMER_NAME      VARCHAR2(100 BYTE),
  CUSTOMER_NUMBER    VARCHAR2(100 BYTE),
  RECEIPT_METHOD     VARCHAR2(30 BYTE),
  RECEIPT_AMOUNT     NUMBER,
  DISCOUNT_AMOUNT    NUMBER,
  ORG_ID             NUMBER,
  GL_DATE            DATE,
  PROCESS_FLAG       VARCHAR2(1 BYTE),
  REQUEST_ID         NUMBER,
  CREATION_DATE      DATE                       DEFAULT SYSDATE,
  CREATED_BY         NUMBER                     DEFAULT 1,
  LAST_UPDATE_DATE   DATE                       DEFAULT SYSDATE,
  LAST_UPDATED_BY    NUMBER                     DEFAULT 1,
  LAST_UPDATE_LOGIN  NUMBER                     DEFAULT 1,
  ERROR_CODE         NUMBER(10),
  ERROR_DESC         VARCHAR2(1000 BYTE),
  ATTRIBUTE1         VARCHAR2(150 BYTE),
  ATTRIBUTE2         VARCHAR2(150 BYTE),
  ATTRIBUTE3         VARCHAR2(150 BYTE),
  ATTRIBUTE4         VARCHAR2(150 BYTE),
  ATTRIBUTE5         VARCHAR2(150 BYTE),
  FILE_NAME          VARCHAR2(150 BYTE),
  REASON_CODE        VARCHAR2(30 BYTE),
  COMMENTS           VARCHAR2(2000 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE INDEX XXQGEN.XXQGEN_CASH_RECEIPT_STG_N1 ON XXQGEN.XXQGEN_CASH_RECEIPT_STG
(REFERENCE_NUMBER, INVOICE_NUMBER, REQUEST_ID)
LOGGING
TABLESPACE XXQGEN
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX XXQGEN.XXQGEN_CASH_RECEIPT_STG_N2 ON XXQGEN.XXQGEN_CASH_RECEIPT_STG
(PROCESS_FLAG, ORG_ID)
LOGGING
TABLESPACE XXQGEN
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
