DROP TABLE XXQGEN.XXQGEN_CLOSED_DROPS_STG CASCADE CONSTRAINTS;

CREATE TABLE XXQGEN.XXQGEN_CLOSED_DROPS_STG
(
  RECORD_ID                   NUMBER,
  SOURCE                      VARCHAR2(240 BYTE),
  PROCESS_FLAG                VARCHAR2(10 BYTE),
  WORK_REQUEST_NBR            VARCHAR2(500 BYTE),
  CONTRACTOR_ID               VARCHAR2(4000 BYTE),
  COMP_CD                     VARCHAR2(4000 BYTE),
  PHONE_NBR                   VARCHAR2(4000 BYTE),
  CONTACT_NM                  VARCHAR2(4000 BYTE),
  STREET_ADDR                 VARCHAR2(4000 BYTE),
  CITY_NM                     VARCHAR2(4000 BYTE),
  STATE_CD                    VARCHAR2(4000 BYTE),
  INVOICE_NBR                 VARCHAR2(500 BYTE),
  BID_AREA_ID                 VARCHAR2(4000 BYTE),
  WIRE_CENTER_ID              VARCHAR2(500 BYTE),
  DROP_PLACED_DT              VARCHAR2(4000 BYTE),
  ACT_QTY                     NUMBER,
  EST_QTY                     NUMBER,
  COST                        VARCHAR2(4000 BYTE),
  ITEM_CATEGORY               VARCHAR2(4000 BYTE),
  ITEM_SUB_CATEGORY           VARCHAR2(4000 BYTE),
  ACT_NUM_WIRES               NUMBER,
  ITEM_ID_A                   VARCHAR2(500 BYTE),
  ACT_QTY_A                   NUMBER,
  ITEM_RATE_AMT_A             VARCHAR2(4000 BYTE),
  ITEM_ID_B                   VARCHAR2(4000 BYTE),
  ACT_QTY_B                   NUMBER,
  ITEM_RATE_AMT_B             VARCHAR2(4000 BYTE),
  MISC_AMT                    VARCHAR2(4000 BYTE),
  NUM_WIRES                   NUMBER,
  ITEM_DEPTH                  NUMBER,
  WIRE_TYPE_CD                VARCHAR2(4000 BYTE),
  WORK_REQUEST_DATE           DATE,
  CUSTOMER_NUMBER             VARCHAR2(100 BYTE),
  REQUEST_ID                  NUMBER,
  ORG_ID                      NUMBER,
  CREATION_DATE               DATE,
  CREATED_BY                  NUMBER,
  LAST_UPDATE_DATE            DATE,
  LAST_UPDATED_BY             NUMBER,
  LAST_UPDATE_LOGIN           NUMBER,
  SERVICE_LINE                VARCHAR2(100 BYTE),
  INCIDENT_ID                 NUMBER,
  PROJECT_ID                  NUMBER,
  TASK_ID                     NUMBER,
  TASK_ASSIGNMENT_ID          NUMBER,
  DEBRIEF_HEADER_ID           NUMBER,
  REV_RECORD_ID               NUMBER,
  ESTIMATE_TASK_TYPE          VARCHAR2(100 BYTE),
  ESTIMATE_PHASE              VARCHAR2(100 BYTE),
  ESTIMATE_SERVICE_ACTIVITY   VARCHAR2(90 BYTE),
  ESTIMATE_CREATE_REQUEST_ID  NUMBER,
  BUDGET_SYNC_REQUEST_ID      NUMBER,
  PROJECT_TASK                VARCHAR2(100 BYTE),
  GROUP_ID                    NUMBER,
  CREW_NUMBER                 VARCHAR2(50 BYTE),
  TASK_CREATE_REQUEST_ID      NUMBER,
  DEBRIEF_CREATE_REQUEST_ID   NUMBER,
  POST_CHARGES_REQUEST_ID     NUMBER,
  REVENUE_INTF_REQUEST_ID     NUMBER,
  REVENUE_PROCESS_REQUEST_ID  NUMBER,
  BILLING_REQUEST_ID          NUMBER,
  ESTIMATE_CREATED_FLAG       VARCHAR2(10 BYTE),
  BUDGET_SYNC_FLAG            VARCHAR2(10 BYTE),
  TASK_CREATED_FLAG           VARCHAR2(10 BYTE),
  DEBRIEF_CREATED_FLAG        VARCHAR2(10 BYTE),
  POST_CHARGES_CREATED_FLAG   VARCHAR2(10 BYTE),
  REVENUE_CREATED_FLAG        VARCHAR2(10 BYTE),
  OPERATION_CREATED_FLAG      VARCHAR2(10 BYTE),
  BILLING_CREATED_FLAG        VARCHAR2(10 BYTE),
  ATTRIBUTE1                  VARCHAR2(250 BYTE),
  ATTRIBUTE2                  VARCHAR2(250 BYTE),
  ATTRIBUTE3                  VARCHAR2(250 BYTE),
  ATTRIBUTE4                  VARCHAR2(250 BYTE),
  ATTRIBUTE5                  VARCHAR2(250 BYTE),
  ATTRIBUTE6                  VARCHAR2(250 BYTE),
  ATTRIBUTE7                  VARCHAR2(250 BYTE),
  ATTRIBUTE8                  VARCHAR2(250 BYTE),
  ATTRIBUTE9                  VARCHAR2(250 BYTE),
  ATTRIBUTE10                 VARCHAR2(250 BYTE),
  ATTRIBUTE11                 VARCHAR2(250 BYTE),
  ATTRIBUTE12                 VARCHAR2(250 BYTE),
  ATTRIBUTE13                 VARCHAR2(250 BYTE),
  ATTRIBUTE14                 VARCHAR2(250 BYTE),
  ATTRIBUTE15                 VARCHAR2(250 BYTE),
  ATTRIBUTE16                 VARCHAR2(250 BYTE),
  ATTRIBUTE17                 VARCHAR2(250 BYTE),
  ATTRIBUTE18                 VARCHAR2(250 BYTE),
  ATTRIBUTE19                 VARCHAR2(250 BYTE),
  ATTRIBUTE20                 VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE1            VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE2            VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE3            VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE4            VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE5            VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE6            VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE7            VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE8            VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE9            VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE10           VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE11           VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE12           VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE13           VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE14           VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE15           VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE16           VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE17           VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE18           VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE19           VARCHAR2(250 BYTE),
  EXTRA_ATTRIBUTE20           VARCHAR2(250 BYTE),
  ERROR_MESSAGE               VARCHAR2(4000 BYTE),
  PROMISED_DT                 DATE,
  SUBMITTER_UID               VARCHAR2(4000 BYTE),
  CUTOVER_REQ_IND             VARCHAR2(4000 BYTE),
  MISC_ITEM_REMARKS           VARCHAR2(4000 BYTE),
  HELD_ORD_IND                VARCHAR2(4000 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE INDEX XXQGEN.XXQGEN_CLOSED_DROPS_STG_N1 ON XXQGEN.XXQGEN_CLOSED_DROPS_STG
(REQUEST_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX XXQGEN.XXQGEN_CLOSED_DROPS_STG_N2 ON XXQGEN.XXQGEN_CLOSED_DROPS_STG
(REQUEST_ID, PROCESS_FLAG)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX XXQGEN.XXQGEN_CLOSED_DROPS_STG_N3 ON XXQGEN.XXQGEN_CLOSED_DROPS_STG
(WORK_REQUEST_NBR, INVOICE_NBR, WIRE_CENTER_ID, ITEM_ID_A, WORK_REQUEST_DATE, 
ORG_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX XXQGEN.XXQGEN_CLOSED_DROPS_STG_N4 ON XXQGEN.XXQGEN_CLOSED_DROPS_STG
(RECORD_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
