OPTIONS ( SKIP=1, ERRORS=10000, DIRECT=FALSE)

LOAD DATA
INFILE XXQGEN_TEST_DK.csv

INTO TABLE XXQGEN_TEST_DK
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'

(ID 	"COMMON_UTILS_PKG_DK.REMOVE_SPL_CHAR(REPLACE(LTRIM(RTRIM(:ID)),CHR(34),NULL))", 
Name	"COMMON_UTILS_PKG_DK.REMOVE_SPL_CHAR(REPLACE(LTRIM(RTRIM(:Name)),CHR(34),NULL))",
Phone	"COMMON_UTILS_PKG_DK.REMOVE_SPL_CHAR(REPLACE(LTRIM(RTRIM(:Phone)),CHR(34),NULL))",
Email	"COMMON_UTILS_PKG_DK.REMOVE_SPL_CHAR(REPLACE(LTRIM(RTRIM(:Email)),CHR(34),NULL))"
)