-- Purchase Order: header
SELECT PHA.AGENT_ID,
         PAPF.FULL_NAME AGENT_NAME,
         PHA.SEGMENT1,
         PHA.VENDOR_ID,
         ASP.VENDOR_NAME,
         ASP.EMPLOYEE_ID,
         ASP.INVOICE_CURRENCY_CODE,
         PHA.VENDOR_CONTACT_ID,
         ASCS. PHONE VENDOR_CONTACT_ADD,
         PHA.VENDOR_SITE_ID,
         ASSA.VENDOR_SITE_CODE,
         ASSA.ADDRESS_LINE1|| ' ' || CITY || ' ' || STATE || ' ' || ZIP || ' ' || PROVINCE || ' ' || ASSA.COUNTRY FULL_ADDRESS,
         ASSA.ORG_ID,
         HOU.NAME,
         ASSA.LOCATION_ID,
         PHA.SHIP_TO_LOCATION_ID,
         HLA.LOCATION_CODE SHIP_TO_LOCATION_CODE,
         HLA.DESCRIPTION SHIP_TO_LOCATION_NAME,
         PHA.BILL_TO_LOCATION_ID,
         HLA.LOCATION_CODE SHIP_TO_LOCATION_CODE,
         HLA.DESCRIPTION SHIP_TO_LOCATION_NAME,
         PHA.CREATION_DATE,
         PHA.START_DATE,
         PHA.END_DATE,
         PHA.AUTHORIZATION_STATUS,
         PLC.LOOKUP_CODE,
         PHA.APPROVED_FLAG,
         PHA.APPROVED_DATE,
         PHA.AMOUNT_LIMIT,
         PHA.ORG_ID,
         HOU.NAME ORG_NAME
FROM PO_HEADERS_ALL PHA,
         PER_ALL_PEOPLE_F PAPF,
         HR_OPERATING_UNITS HOU,
         AP_SUPPLIERS ASP,
         AP_SUPPLIER_SITES_ALL ASSA,
         AP_SUPPLIER_CONTACTS ASCS,
         HR_LOCATIONS_ALL HLA,
          PO_DOCUMENT_TYPES_ALL_VL PDTAV,
          PO_LOOKUP_CODES PLC
WHERE 1=1
    AND HOU.ORGANIZATION_ID = PHA.ORG_ID
    AND ASP.VENDOR_ID = PHA.VENDOR_ID
    AND ASSA.VENDOR_ID = ASP.VENDOR_ID
    AND ASSA.ORG_ID = HOU.ORGANIZATION_ID
    AND ASSA.VENDOR_SITE_ID = PHA.VENDOR_SITE_ID
    AND ASCS.VENDOR_SITE_ID(+)= ASSA.VENDOR_SITE_ID
    AND HLA.LOCATION_ID = PHA.SHIP_TO_LOCATION_ID
    AND HLA.LOCATION_ID = PHA.BILL_TO_LOCATION_ID
    AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
    AND PAPF.PERSON_ID = PHA.AGENT_ID
    and PHA.AUTHORIZATION_STATUS = PLC.LOOKUP_CODE
    AND PLC.LOOKUP_TYPE= 'AUTHORIZATION STATUS'
    AND  PHA.TYPE_LOOKUP_CODE = PDTAV.DOCUMENT_SUBTYPE
    AND PDTAV.ORG_ID = HOU.ORGANIZATION_ID
    AND PDTAV.DOCUMENT_TYPE_CODE = 'PO'
    AND PHA.SEGMENT1 = '3062';

-- Purchase Order: Lines
SELECT PLA.PO_LINE_ID,
            PLA.PO_HEADER_ID,
            PLA.LINE_TYPE_ID,
            PLA.LINE_NUM,
            PLA.ITEM_ID,
            PLA.ITEM_REVISION,
            PLA.CATEGORY_ID,
            PLA.ITEM_DESCRIPTION,
            PLA.LIST_PRICE_PER_UNIT,
            PLA.UNIT_PRICE,
            PLA.QUANTITY,
            PLA.UN_NUMBER_ID,
            PLA.BASE_QTY,
            PLA.BASE_UOM,
            PLA.PROJECT_ID,
            PLA.TASK_ID,
            PLA.LINE_REFERENCE_NUM,
            PLA.JOB_ID
FROM 
            PO_LINES_ALL PLA,
            PO_HEADERS_ALL PHA,
            MTL_SYSTEM_ITEMS_B MSIB,
            MTL_CATEGORIES MC,
            PO_LINE_TYPES MLT,
            ORG_ORGANIZATION_DEFINITIONS OOD,
            PO_LINE_LOCATIONS_ALL PLLA
WHERE 1=1
    AND PLA.PO_HEADER_ID = PHA.PO_HEADER_ID
    AND MSIB.INVENTORY_ITEM_ID = PLA.ITEM_ID
    AND MC.CATEGORY_ID = PLA.CATEGORY_ID
    AND MLT.LINE_TYPE_ID = PLA.LINE_TYPE_ID
    AND OOD.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
    AND PLLA.PO_LINE_ID = PLA.PO_LINE_ID
    --AND PLA.ORG_ID = MSIB.ORGANIZATION_ID
    AND PLLA.SHIP_TO_ORGANIZATION_ID = MSIB.ORGANIZATION_ID
    AND OOD.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
    --AND HOU.ORGANIZATION_ID = PHA.ORG_ID
    AND PHA.SEGMENT1 = '3062'
--    AND PHA.ORG_ID=1759
    ;
    
-- Purchase Order: Distribution
SELECT PDA.PO_DISTRIBUTION_ID,
            PDA.PO_HEADER_ID,
            PDA.PO_LINE_ID,
            PDA.LINE_LOCATION_ID,
            PDA.SET_OF_BOOKS_ID,
            PDA.CODE_COMBINATION_ID,
            PDA.QUANTITY_ORDERED,
            PDA.QUANTITY_DELIVERED,
            PDA.QUANTITY_CANCELLED,
            PDA.AMOUNT_BILLED,
            PDA.DESTINATION_TYPE_CODE,
            PDA.DESTINATION_ORGANIZATION_ID,
            PDA.DISTRIBUTION_TYPE,
            GCC.SEGMENT1 || '-' || GCC.SEGMENT2 || '-' || GCC.SEGMENT3 || '-' || GCC.SEGMENT4 || '-' || GCC.SEGMENT5 CHARGE_ACC
FROM    PO_DISTRIBUTIONS_ALL PDA,
            PO_HEADERS_ALL PHA,
            PO_LINES_ALL PLA,
            GL_CODE_COMBINATIONS GCC
WHERE 1=1
    AND PHA.PO_HEADER_ID = PDA.PO_HEADER_ID
    AND PLA.PO_LINE_ID = PDA.PO_LINE_ID
    AND PHA.SEGMENT1 = '3062'
    AND GCC.CODE_COMBINATION_ID = PDA.CODE_COMBINATION_ID;

