SELECT 
    RQHA.SEGMENT1,
    PAPF.PERSON_ID PREPARER_ID,
    FU.USER_ID LAST_UPDATED_BY,
    FU.USER_NAME CREATED_BY,
    RQHA.DESCRIPTION,
    RQHA.TYPE_LOOKUP_CODE TYPEE,
    PLC.LOOKUP_CODE,
    HOU.ORGANIZATION_ID ORG_ID
FROM
    PO_REQUISITION_HEADERS_ALL RQHA,
    PER_ALL_PEOPLE_F PAPF,
    FND_USER FU,
    PO_DOCUMENT_TYPES_ALL_VL PDT,
    PO_LOOKUP_CODES PLC,
    HR_OPERATING_UNITS HOU
WHERE
    RQHA.PREPARER_ID=PAPF.PERSON_ID
   AND RQHA.LAST_UPDATED_BY = FU.USER_ID
   AND RQHA.AUTHORIZATION_STATUS =PLC. LOOKUP_CODE
   AND PLC. LOOKUP_TYPE ='AUTHORIZATION STATUS'
   AND RQHA.TYPE_LOOKUP_CODE=PDT.DOCUMENT_SUBTYPE
   AND RQHA.ORG_ID=PDT.ORG_ID
   AND PDT.DOCUMENT_TYPE_CODE = 'REQUISITION'
   AND RQHA.ORG_ID=HOU.ORGANIZATION_ID
   AND RQHA.SEGMENT1='14438'
;