create or replace package XXQGEN_UTL_OUTBOND_DK
AS
    
    GC_CONC_ID                  NUMBER            := FND_PROFILE.VALUE('CONC_REQUEST_ID');
    GC_LOCATION                 VARCHAR(30)     := 'XXQGEN_GOODS_DK';

    PROCEDURE BOC_UTL_DATA;
    PROCEDURE MAIN(ERRBUF OUT VARCHAR, RETCODE OUT VARCHAR);
END XXQGEN_UTL_OUTBOND_DK;