#!/bin/sh
##==================================================================================================================================
##PROGRAM         :XXQGEN
##TYPE            :
##UNIX LOCATION   :/u01/XXQGEN/fs1/EBSapps/appl/XXQGEN/12.0.0/bin  ** This UNIX Location is for XXQGEN **
##
##
##INSERTS INTO    :XX
##CALLED BY       :
##
##==================================================================================================================================
##DESCRIPTION:
##
##   This is the Host file used by Concurrent Program to Upload CSV File data FROM the directory into the XX Database
##   table. It is called by the " " Concurrent Program.
##
##   The " "  will then be run to Load FS Setup Customer,Job Type,City-State,Market values 
##
##==================================================================================================================================
##PRE-REQUISITES:
##
##   XX table must be Created in Custom Schema.
##
##==================================================================================================================================
##HISTORY:
##
##  WHEN      	  PROGRAMMER         SNOW REQ#    SNOW CHG#   STAT CSR  DESCRIPTION
##  --------- 	  -----------------  -----------  ----------  --------  ----------------------------------------------------------------
##  
##==================================================================================================================================

#######################################################
#                                                     #
#              FUNCTION - DATALOAD                    #
#                                                     # 
#######################################################

dataload ()
{
DATA_SOURCE=`echo $1`
echo "DATA_SOURCE: $DATA_SOURCE"
CTL_FILE=$CTL_DIR/"XXQGEN_SETUP_APPL_${DATA_SOURCE}.ctl"
DATA_FILE=$CSV_DIR/inbound/$file
LOG_FILE=$CSV_DIR/error/${file%."csv"}_$REQUEST_ID."log"
BAD_FILE=$CSV_DIR/error/${file%."csv"}_$REQUEST_ID."bad"
DIS_FILE=$CSV_DIR/error/${file%."csv"}_$REQUEST_ID."dis"
ARCH_FILE=$CSV_DIR/arch/${file%."csv"}_$REQUEST_ID."csv"

sqlldr userid=$P_LOGIN control=$CTL_FILE log=$LOG_FILE data=$DATA_FILE bad=$BAD_FILE discard=$DIS_FILE

echo "SQL*Loader execution successful" 

cp $DATA_FILE $ARCH_FILE
rm $DATA_FILE

echo "The data file has been copied successfully to the Archive Directory."

}

#################################################
#                                               #
#                    M A I N                    #
#                                               #
#################################################
#                                               #
#            Program Starts From Here           #
#                                               #
#################################################

echo "Setting Parameters"

P_LOGIN=`echo $1 | cut -f2 -d '"'`
P_USERNAME=`echo $P_LOGIN | cut -f1 -d '/'`
P_REQID=`echo $1 | cut -f2 -d " " | cut -f2 -d "="`
CTL_DIR=`echo $1 | cut -f8 -d '"'`
CSV_DIR=`echo $1 | cut -f10 -d '"'`
REQUEST_ID=`echo $1 | cut -f12 -d '"'`

 echo "Script to copy the data from flat file to the FS Setup Mapping interface table. \n"

 echo "***************************** Parameter Listing *****************************\n"
 echo "Request Id                            : $P_REQID"
 echo "Username                              : $P_USERNAME"
 echo "Control File Directory                : $CTL_DIR"
 echo "CSV File Directory                    : $CSV_DIR"
 echo "Request ID                            : $REQUEST_ID"
 echo "\n*****************************************************************************\n"

cd $CSV_DIR/inbound

for file in *.csv
do

echo "File Name :$file"

if [ -s $file ]; 
then

if [[ $file == XXQGEN_SETUP_TEMPLATE_BUSINESS_PROCESS*.csv ]];
then

dataload "BP"

elif [[ $file == XXQGEN_SETUP_TEMPLATE_CUSTOMER*.csv ]];
then

dataload "CUST"

elif [[ $file == XXQGEN_SETUP_TEMPLATE_JOB_TYPE*.csv ]];
then

dataload "JT"

elif [[ $file == XXQGEN_SETUP_TEMPLATE_STATE_CITY*.csv ]];
then

dataload "STATE"

elif [[ $file == XXQGEN_SETUP_TEMPLATE_MARKET*.csv ]];
then

dataload "INV"

else

echo "The data file name should be in this format: XXQGEN_SETUP_TEMPLATE_<RECORD_TYPE><XYZ>.csv"

fi

else

echo "The data files doesn't exist in the directory or the file name has spaces.Please remove the spaces from the file name and retry again." 

fi
done