--TABLE CREATION OF PRAGMA AUTONOMOUS

CREATE TABLE XXQGEN_PRAGMA_AUTO_TEST_DK(
    ID              NUMBER,
    NAME        VARCHAR2(300)
);


--FOR INSERT AN ERROR LOG

CREATE TABLE XXQGEN_PRAGMA_AUTO_TEST_LOG_DK(
    ERROR_MESSAGE       VARCHAR2(400),
    ERROR_DATE              DATE
);


SELECT *
FROM XXQGEN_PRAGMA_AUTO_TEST_DK;

SELECT *
FROM XXQGEN_PRAGMA_AUTO_TEST_LOG_DK;