-- HRMS QUERY 1

SELECT DISTINCT PAF.ASSIGNMENT_ID,
            PAF.BUSINESS_GROUP_ID,
            PBG.NAME BUSI_GRP_NAME,
            PBG.NAME,
            PAF.EFFECTIVE_START_DATE,
            PAF.EFFECTIVE_END_DATE,
            PAF.JOB_ID,
            PJ.NAME JOB_NAME,
            PAF.POSITION_ID,
            PAP.NAME POSITION_NAME,
            PAF.GRADE_ID,
            PG.NAME JOB_NAME,
            PAF.LOCATION_ID,
            HL.LOCATION_CODE LOC_NAME,
            PAF.SUPERVISOR_ID,
            PAPF2.FULL_NAME,
            PAF.ORGANIZATION_ID,
            HAOU.NAME ORG_NAME,
            PAF.DEFAULT_CODE_COMB_ID,
            GCC.SEGMENT1 || '-' || GCC.SEGMENT2 || '-' || GCC.SEGMENT3 || '-' || GCC.SEGMENT4 ACCOUNT,
            PAF.PERIOD_OF_SERVICE_ID,
            PAF.TITLE,
            PAF.NOTICE_PERIOD,
            PAF.WORK_AT_HOME
FROM PER_ASSIGNMENTS_F PAF,
         PER_ADDRESSES PA,
         PER_BUSINESS_GROUPS PBG,
         PER_PERSON_TYPE_USAGES_F PPTUF,
         PER_PERSON_TYPES PPT,
         PER_JOBS PJ,
         PER_ALL_PEOPLE_F PAPF,
         PER_ALL_POSITIONS PAP,
         PER_GRADES PG,
         HR_LOCATIONS HL,
         PER_ALL_PEOPLE_F PAPF2,
         HR_ALL_ORGANIZATION_UNITS HAOU,
         GL_CODE_COMBINATIONS GCC
WHERE 1=1
    AND PAF.PERSON_ID = PA.PERSON_ID(+)
    AND PAF.BUSINESS_GROUP_ID = PBG.BUSINESS_GROUP_ID
    AND PAF.JOB_ID = PJ.JOB_ID(+)
    AND PAPF.PERSON_ID = PPTUF.PERSON_ID(+)
    AND PAPF.PERSON_TYPE_ID = PPTUF.PERSON_TYPE_ID(+)
    AND PAF.PERSON_ID = PAPF.PERSON_ID(+)
    AND PAPF.PERSON_TYPE_ID = PPT.PERSON_TYPE_ID
    AND SYSDATE BETWEEN TRUNC(PAPF.EFFECTIVE_START_DATE) AND TRUNC(PAPF.EFFECTIVE_END_DATE)
    AND (PAPF.CURRENT_EMPLOYEE_FLAG = 'Y'
            OR
            PAPF.CURRENT_NPW_FLAG = 'Y')
    AND PAF.POSITION_ID = PAP.POSITION_ID(+)
    AND PAF.GRADE_ID = PG.GRADE_ID(+)
    AND PAF.LOCATION_ID = HL.LOCATION_ID(+)
    AND PAPF2.PERSON_ID(+) = PAF.SUPERVISOR_ID
    AND SYSDATE BETWEEN TRUNC(PAPF2.EFFECTIVE_START_DATE) AND TRUNC(PAPF2.EFFECTIVE_END_DATE)
    AND (PAPF2.CURRENT_EMPLOYEE_FLAG = 'Y'
            OR
            PAPF2.CURRENT_NPW_FLAG = 'Y')
    AND PAF.ORGANIZATION_ID = HAOU.ORGANIZATION_ID
    AND PAF.DEFAULT_CODE_COMB_ID = GCC.CODE_COMBINATION_ID(+)
    AND SYSDATE BETWEEN TRUNC(PAF.EFFECTIVE_START_DATE) AND TRUNC(PAF.EFFECTIVE_END_DATE)
    --AND PAF.PERSON_ID = 377;
    
--    RECORD_TYPE: 1912


SELECT *
FROM PER_ASSIGNMENTS_F;